// <auto-generated />
using ASPNETCORE_GCSMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPNETCORE_GCSMS.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNETCORE_GCSMS.Data.DbModels.Etablissement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Ehpad");

                    b.Property<int?>("Fah");

                    b.Property<int?>("Fam");

                    b.Property<int?>("Foyer");

                    b.Property<string>("IframeGoogle");

                    b.Property<int?>("Jour");

                    b.Property<string>("Nom");

                    b.Property<int?>("Pasa");

                    b.Property<int?>("Temporaire");

                    b.Property<int?>("Uhr");

                    b.Property<int?>("Usa");

                    b.HasKey("Id");

                    b.ToTable("GCSMS_Etablissement");
                });

            modelBuilder.Entity("ASPNETCORE_GCSMS.Data.DbModels.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categorie");

                    b.Property<string>("Content");

                    b.Property<int>("Position");

                    b.HasKey("Id");

                    b.ToTable("GCSMS_Formation");
                });

            modelBuilder.Entity("ASPNETCORE_GCSMS.Data.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EtablissementId");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("EtablissementId");

                    b.ToTable("GCSMS_Users");
                });

            modelBuilder.Entity("ASPNETCORE_GCSMS.DbModels.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int?>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("GCSMS_Posts");
                });

            modelBuilder.Entity("ASPNETCORE_GCSMS.Data.DbModels.User", b =>
                {
                    b.HasOne("ASPNETCORE_GCSMS.Data.DbModels.Etablissement")
                        .WithMany("Users")
                        .HasForeignKey("EtablissementId");
                });

            modelBuilder.Entity("ASPNETCORE_GCSMS.DbModels.Post", b =>
                {
                    b.HasOne("ASPNETCORE_GCSMS.Data.DbModels.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
