INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Ancy le Franc Ehpad "Résidence les Fontenottes"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Auxerre Maison Départementale Retraite Yonne');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Brienon sur Armançon Ehpad "Résidence Joséphine Normand"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Champcevrais Ehpad "Château de Bouron"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Charny Ehpad "Résidence Vallée de l''Ouanne"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Châtel Censoir Ehpad "Résidence La Chatonnière"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Coulanges sur Yonne Ehpad "Résidence Ste Clotilde"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Courson les Carrières Ehpad');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Isle sur Serein Ehpad');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Nantou-Pourrain Ehpad "Château de Nantou"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Noyers sur Serein Ehpad');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Pont sur Yonne et Villeblevin Ehpad "Résidence Lamy-Delettrez"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Ravières Ehpad "Résidence Camille Rizier"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Saint Bris le Vineux Ehpad "Résidence des Côteaux"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Saint Fargeau Ehpad "Résidence du Moulin de l''Arche"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Saint Julien du Sault Ehpad "Résidence St Julien"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Saint Sauveur en Puisaye Ehpad "Résidence Gandrille en bel air"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Seignelay Ehpad "Résidence Colbert"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Thizy Ehpad');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Toucy Ehpad "Résidence de la croix des vignes"');
INSERT INTO GCSMS_ETABLISSEMENT (Nom) VALUES ('Vermenton Ehpad "Résidence François Collet"');